### PR TITLE
Print available commands when `--help` flag is provided

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/build/build.go` line 196 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29#-NtLXXbJ2F2hIoTCdgAZ:-NtLXXbJ2F2hIoTCdgA_:b-1mrb0b) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/5d605aec6a863321f3114afc39796a19d9a1fa1e/pkg/build/build.go#L196)):*
> ```Go
> 	}
> 	fmt.Println("\n Available commands:")
> 	fmt.Println()
> ```

With `Printf` you won't need that line
___
*[`pkg/build/build.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29#-NtLXbIP7sO1zjuHZMwu:-NtLXbIP7sO1zjuHZMwv:b28fujj) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/5d605aec6a863321f3114afc39796a19d9a1fa1e/pkg/build/build.go#L200)):*
> ```Go
> 		fmt.Printf(fmt.Sprintf(`   %%-%ds`, maxLen)+"  %s\n", path, commands[path].Description)
> 	}
> 	fmt.Println("")
> ```

Why do you need the empty string inside the func? Also I see that in prev `fmt.Printf` you already have new line. Do you need additional?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/build/build.go` line 196 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29#-NtLXXbJ2F2hIoTCdgAZ:-NtPj_fo6e_4GEzaYrYF:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/5d605aec6a863321f3114afc39796a19d9a1fa1e/pkg/build/build.go#L196)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

With `Printf` you won't need that line
</blockquote></details>

Done.
___
*[`pkg/build/build.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29#-NtLXbIP7sO1zjuHZMwu:-NtPj_xB5JdvMUp-cwat:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/5d605aec6a863321f3114afc39796a19d9a1fa1e/pkg/build/build.go#L200)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need the empty string inside the func? Also I see that in prev `fmt.Printf` you already have new line. Do you need additional?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
