### PR TITLE
Return nil form run signals if context is canceled.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Return nil form run signals if context is canceled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/parallel/group.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlt-C9QAxuazUrgSQuw:-Nlt-C9QAxuazUrgSQux:b5sc40y) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/0df49f4937c2d3ed28610e853b3e0036f6df0de7/pkg/parallel/group.go#L145)):*
> ```Go
> func (g *Group) runTask(ctx context.Context, name string, id int64, onExit OnExit, task Task) {
> 	err := runTaskWithRecovery(ctx, g.log, name, id, onExit, task)
> 	if err != nil && !errors.Is(err, context.Canceled) {
> ```

Or we can print debug always as another approach.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/parallel/group.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlt-C9QAxuazUrgSQuw:-NlvzamxC5RXY-Clut0W:b-qs4g2m) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/0df49f4937c2d3ed28610e853b3e0036f6df0de7/pkg/parallel/group.go#L145)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Or we can print debug always as another approach.
</blockquote></details>

I disagree. Error is an error. Error is returned and that's it. Parallel cannot know if this is intended or not. Task returned successfuly is only the one where error is nil.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/parallel/group.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlt-C9QAxuazUrgSQuw:-NlwKPL10DlJcGr_3AgJ:blmj2g4) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/0df49f4937c2d3ed28610e853b3e0036f6df0de7/pkg/parallel/group.go#L145)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I disagree. Error is an error. Error is returned and that's it. Parallel cannot know if this is intended or not. Task returned successfuly is only the one where error is nil.
</blockquote></details>

Just try to run 
```go
run.Tool("tool", func(ctx context.Context) error {  
    return nil  
})
```
And you will see that error is printed, but the tool executed successfully.
The reason for this is, `"signals"` spawn func, which ends with the context error.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/parallel/group.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlt-C9QAxuazUrgSQuw:-Nlwa9bi2NrOVJE8kw75:b-j418zt) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/0df49f4937c2d3ed28610e853b3e0036f6df0de7/pkg/parallel/group.go#L145)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Just try to run 
```go
run.Tool("tool", func(ctx context.Context) error {  
    return nil  
})
```
And you will see that error is printed, but the tool executed successfully.
The reason for this is, `"signals"` spawn func, which ends with the context error.
</blockquote></details>

so the correct way to fix it is to return `nil` from `signals`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/parallel/group.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlt-C9QAxuazUrgSQuw:-Nlwgc0C4eJQOYUwQpD_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/0df49f4937c2d3ed28610e853b3e0036f6df0de7/pkg/parallel/group.go#L145)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so the correct way to fix it is to return `nil` from `signals`
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`pkg/run/run.go` line 56 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlwt7f6CDisNPoUkGci:-Nlwt7f79IqlnpPCuPbt:b-yahmvl) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/863de741dd0c881dd53732a6b4d0cbc169f032f9/pkg/run/run.go#L56)):*
> ```Go
> 			select {
> 			case <-ctx.Done():
> 				return nil
> ```

I am not sure, but I think it can be both cancelled and timed out, do you want to ignore both ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`pkg/run/run.go` line 56 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25#-Nlwt7f6CDisNPoUkGci:-NlwvbTS90MmOGtTY6Ej:b-l9gjle) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/863de741dd0c881dd53732a6b4d0cbc169f032f9/pkg/run/run.go#L56)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not sure, but I think it can be both cancelled and timed out, do you want to ignore both ?
</blockquote></details>

Good point. Only canceled. Updated.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
