### PR TITLE
Refactor parallel to be able to use custom loggers.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/logger/logger.go` line 64 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjCie-pi5TT-VM93g:-NkKjCie-pi5TT-VM93h:berin6s) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/logger/logger.go#L64)):*
> ```Go
> 	defer mu.Unlock()
> 
> 	log := ctx.Value(logField)
> ```

I think we use this code in a lot of places and it might brake compatibility once we upgrade this library in crust eg. ?
Or it should be fine ? 
___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjkhEEEumWSMvXTnt:-NkKjkhEEEumWSMvXTnu:b8l4cot) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
> ```Go
> 
> // NoOptsLogger is no opts log.
> type NoOptsLogger struct{}
> ```

does NoOpts mean no options or that it prints nothing ?
I'm not sure the name is clear for me

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/logger/logger.go` line 64 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjCie-pi5TT-VM93g:-NkL5pQR7CBIiNpYvru7:b-t323vd) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/logger/logger.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we use this code in a lot of places and it might brake compatibility once we upgrade this library in crust eg. ?
Or it should be fine ?
</blockquote></details>

It won't, since currenty it will panic is the log is nil.
___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjkhEEEumWSMvXTnt:-NkL5xS-77idYwFquuRd:bn5cva4) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does NoOpts mean no options or that it prints nothing ?
I'm not sure the name is clear for me
</blockquote></details>

Updated, check the name now.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjkhEEEumWSMvXTnt:-NkLdWz-6M6klylV0-fB:bj86yvm) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated, check the name now.
</blockquote></details>


nit: Noop -> NoOp if you mean `No Operational` :sweat_smile: 
___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkLdkuUCgld15u-Nc4M:-NkLdkuUCgld15u-Nc4N:bmlh0fi) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
> ```Go
> 
> // NoOptsLogger is no opts log.
> type NoOptsLogger struct{}
> ```

should we export this type ? Maybe it should be internal and start with `n`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkKjkhEEEumWSMvXTnt:-NkPSRV001wHeWx8OPMP:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: Noop -> NoOp if you mean `No Operational` :sweat_smile:
</blockquote></details>

Done
___
*[`pkg/parallel/logger.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkLdkuUCgld15u-Nc4M:-NkPSTJX6bcjveeGo0c_:b-5szdmz) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/1a79318dd69b1de8c2dc60e2088e85766e7c614f/pkg/parallel/logger.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we export this type ? Maybe it should be internal and start with `n`
</blockquote></details>

I don't see a reason not to export it.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`pkg/parallel/group.go` line 130 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22#-NkQ1lFm8GxgONiprupt:-NkQ1lFm8GxgONiprupu:b-1qejv6) ([raw file](https://github.com/CoreumFoundation/coreum-tools/blob/7572474a953900e4236ec43a3160b8de199037ce/pkg/parallel/group.go#L130)):*
> ```Go
> 
> 	id := atomic.AddInt64(&nextTaskID, 1)
> 	g.log.Debug(name, fmt.Sprintf("Task spawned, id:%x, onExit: %s", id, onExit.String()))
> ```

I would still love to preserve structured logging

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-tools/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
