### PR TITLE
Change help message

### PR DESCRIPTION
**Pull request by oliverasistemas**
Improve message when `crust` is run without any arguments.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @wojtek-coreum, @xlab, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @xlab, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/build/build.go` line 162 at r1](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15#-N9g0jYo8xf1DmptDEDw:-N9g0jYo8xf1DmptDEDx:b-nhab9e) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7b4e517789a8f0339b923bcf06666eac34ee3411/pkg/build/build.go#L162)):*
> ```Go
> - znet 	Tool used to spin up development environment running the same components which are used in production.
> - lint	Lints source code and checks that git status is clean
> - test  Runs unit and integration tests
> ```

this runs only unit tests

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/build/build.go` line 162 at r1](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15#-N9g0jYo8xf1DmptDEDw:-N9g2edL8siVSYk4NFlH:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7b4e517789a8f0339b923bcf06666eac34ee3411/pkg/build/build.go#L162)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this runs only unit tests
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @xlab, and @ysv)

**Pull request merged**
