### PR TITLE
Fix linting issues and install CI workflow

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16#-N9p-kAP3lBqJd_uf8Kv:-N9p-kAP3lBqJd_uf8Kw:bpizrt8) (no related file):*
This PR contains only mechanical changes required to make linter happy - no changes in business logic

___

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/build/build.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16#-N9pt_Fy2F47dOi5AEwE:-N9pt_Fy2F47dOi5AEwF:b9m8h4z) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/c64045d8e48bd4e5d25bc8587256c1d9c0af76d3/pkg/build/build.go#L116)):*
> ```Go
> 		if r := recover(); r != nil {
> 			var err error
> 			if err2, ok := r.(error); ok {
> ```

I see that it's just a movement of the func ;-) 
But it would look better without the err2, just sending the error to the channel as soon as you get it.

**Review by ysv — CHANGES_REQUESTED** [review]
I disagree with an approach we took here to introduce crust in coreum-tools

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16#-:-N9q5trb3G8QWykHr120:b-r93w7z)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

**Review by ysv — CHANGES_REQUESTED** [review]
Blocking this PR for now

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16#-:-N9q6-P75gNxRMWmlQtH:bn7qeal)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @xlab)

___
*[`pkg/build/build.go` line 116 at r1](https://reviewable.io/reviews/coreumfoundation/coreum-tools/16#-N9pt_Fy2F47dOi5AEwE:-N9qAWEO7PfxaWF6ty10:bmh3of5) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/c64045d8e48bd4e5d25bc8587256c1d9c0af76d3/pkg/build/build.go#L116)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see that it's just a movement of the func ;-) 
But it would look better without the err2, just sending the error to the channel as soon as you get it.
</blockquote></details>

As I wrote at the beginning, this PR is only about mechanical changes required to make linter happy. I would like to redo the logic anyway, remove IoC in the first place. But not here.

**Pull request closed without merging**
